[package]
name = "Helloworldsampleenclave"
version = "0.1.0"
authors = ["Baidu"]

[lib]
name = "helloworldsampleenclave"
crate-type = ["staticlib"]

[features]
default = []
use_std = []

[dependencies]
sgx_types = { path = "../../../sgx_types" }
sgx_tstdc = { path = "../../../sgx_tstdc" }
